// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHgqnFKtHMOf221rA9xkzZ4jHSAFuHA0',
    appId: '1:1027133317252:web:96df8b0c87caa87d0862d1',
    messagingSenderId: '1027133317252',
    projectId: 'form-fec8e',
    authDomain: 'form-fec8e.firebaseapp.com',
    storageBucket: 'form-fec8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBad82fCHysqGfLj9pDce8Hne-QC3q9kW8',
    appId: '1:1027133317252:android:f4e0f435d4e431950862d1',
    messagingSenderId: '1027133317252',
    projectId: 'form-fec8e',
    storageBucket: 'form-fec8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIaYKnDUEwMudPSjTbg6Og-KdZQTdV8DA',
    appId: '1:1027133317252:ios:8a2292d47957e87e0862d1',
    messagingSenderId: '1027133317252',
    projectId: 'form-fec8e',
    storageBucket: 'form-fec8e.appspot.com',
    iosBundleId: 'com.example.formfill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIaYKnDUEwMudPSjTbg6Og-KdZQTdV8DA',
    appId: '1:1027133317252:ios:8a2292d47957e87e0862d1',
    messagingSenderId: '1027133317252',
    projectId: 'form-fec8e',
    storageBucket: 'form-fec8e.appspot.com',
    iosBundleId: 'com.example.formfill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBHgqnFKtHMOf221rA9xkzZ4jHSAFuHA0',
    appId: '1:1027133317252:web:7f4f7cbfc48025120862d1',
    messagingSenderId: '1027133317252',
    projectId: 'form-fec8e',
    authDomain: 'form-fec8e.firebaseapp.com',
    storageBucket: 'form-fec8e.appspot.com',
  );
}
